- hosts: localhost
  become: true
  tasks: 
  
  - name: Upgrade system
    apt:
      upgrade: dist
      update_cache: yes
      autoremove: yes
      
  - name: Install packages
    package:
      name:
        - 0ad
        - adwaita-qt
        - audacity
        - blender
        - brasero
        - clamtk
        - evolution-ews
        - ffmpeg
        - filezilla
        - firefox-esr
        - firmware-linux-nonfree
        - flatpak
        - freecad
        - frogatto
        - gchempaint
        - gcu-bin
        - ghostwriter
        - gimp
        - gnome-mastermind
        - gnome-shell-extension-caffeine
        - gnome-software-plugin-flatpak
        - gnome-subtitles
        - handbrake
        - homebank
        - ibus-libpinyin
        - imagej
        - inkscape
        - keepassxc
        - lame
        - lyx
        - mp3wrap
        - mkvtoolnix-gui
        - mp3wrap
        - musescore3
        - nautilus-nextcloud
        - nextcloud-desktop
        - openssh-server
        - pandoc
        - pdfarranger
        - python3-pip
        - pitivi
        - pronterface
        - prusa-slicer
        - puddletag
        - qt5-gtk-platformtheme
        - qt5-style-plugins
        - r-base
        - r-cran-rcmdr
        - remmina
        - rhythmbox-plugin-alternative-toolbar
        - simplescreenrecorder
        - soundconverter
        - sound-juicer
        - supertux
        - supertuxkart
        - torbrowser-launcher
        - ttf-mscorefonts-installer
        - unattended-upgrades
        - unknown-horizons
        - virtualbox
        - virtualbox-guest-additions-iso
        - warzone2100
        - webext-https-everywhere
        - webext-privacy-badger
        - webext-ublock-origin-firefox
      state: latest
      
  - name: Uninstall packages
    package:
      name:
        - chromium
        - epiphany-browser
        - synaptic
      state: absent      
    
  - name: Enable FlatHub
    flatpak_remote:
      name: flathub
      flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
      method: system
      state: present
      
  - name: Install flatpaks
    flatpak:
      name: "{{item}}"
      method: system
      state: present
    with_items:
      - com.github.johnfactotum.Foliate
      - com.github.tchx84.Flatseal
      - com.microsoft.Teams
      - edu.mit.Scratch
      - io.freetubeapp.FreeTube
      - org.jitsi.jitsi-meet
      - org.zotero.Zotero
      - uk.co.ibboard.cawbird
      - us.zoom.Zoom
    when: ansible_architecture == "x86_64"
    
  - name: Update Python modules
    pip:
      name:
        - pip
        - yt-dlp
      state: latest
  
  - name: Uninstall youtube-dl
    pip:
      name:
        - youtube-dl
      state: absent
      
  - name: Schedule maintenance
    cron:
      name: "Hourly ansible-pull config"
      job: "ansible-pull -U https://github.com/ngkengwooi/desktop-config debian-home.yml"
      minute: "0"
      user: root
