- hosts: localhost
  become: true
  tasks:   
  - name: Upgrade system
    apt:
      upgrade: dist
      update_cache: yes
      autoremove: yes    
  - name: Install packages
    package:
      name:
        - adwaita-qt
        - ffmpeg
        - filezilla
        - firefox-esr
        - firmware-linux-nonfree
        - flatpak
        - freecad
        - gchempaint
        - gcu-bin
        - ghostwriter
        - gimp
        - gnome-shell-extension-caffeine
        - gnome-software-plugin-flatpak
        - grsync
        - ibus-libpinyin
        - imagej
        - inkscape
        - lame
        - lyx
        - openssh-server
        - pdfarranger
        - pronterface
        - python3-pip
        - qt5-gtk-platformtheme
        - qt5-style-plugins
        - remmina
        - rhythmbox-plugin-alternative-toolbar
        - ttf-mscorefonts-installer
        - unattended-upgrades
        - webext-ublock-origin
      state: latest
      
  - name: Uninstall packages
    package:
      name:
        - chromium
        - frogatto
        - gnome-games
        - gnome-software
        - prusa-slicer # Install flatpak version instead
        - synaptic
        - webext-https-everywhere # No longer needed, now shipped with Firefox
      state: absent    
    
  - name: Enable FlatHub
    flatpak_remote:
      name: flathub
      flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
      method: system
      state: present
      
  - name: Install flatpaks
    flatpak:
      name: "{{item}}"
      method: system
      state: present
    with_items:
      - com.prusa3d.PrusaSlicer
      - org.zotero.Zotero
      - us.zoom.Zoom
    when: ansible_architecture == "x86_64"
    
  - name: Uninstall flatpaks
    flatpak:
      name: "{{item}}"
      method: system
      state: absent
    with_items:
      - org.mozilla.firefox
    when: ansible_architecture == "x86_64"
    
  # Do not install Python packages using pip without venv
  - name: Uninstall Python modules
    pip:
      name:
        - pip
        - yt-dlp
      state: absent
      
  - name: Schedule maintenance
    cron:
      name: "Hourly ansible-pull config"
      job: "ansible-pull -U https://github.com/ngkengwooi/desktop-config debian-lab-gnome.yml"
      minute: "0"
      user: root
