- hosts: localhost
  become: true
  tasks:
  
  - name: Upgrade system
    apt:
      upgrade: dist
      update_cache: yes
      autoremove: yes
      
  - name: Install packages
    package:
      name:
        - task-xfce-desktop
        - arc-theme
        - cheese
        - ffmpeg
        - firefox-esr
        - firmware-b43-installer
        - firmware-linux-nonfree
        - fonts-roboto
        - freecad
        - gimp
        - grub-customizer
        - imagej
        - inkscape
        - lame
        - lightdm-gtk-greeter-settings
        - moka-icon-theme
        - p7zip-full
        - pdfarranger
        - pronterface
        - prusa-slicer
        - python3-pip
        - qt5-gtk-platformtheme
        - qt5-style-plugins        
        - ttf-mscorefonts-installer
        - unattended-upgrades
        - unrar
        - vlc
        - wireguard
      state: latest
      
  - name: Uninstall packages
    package:
      name:
        - adapta-gtk-theme
        - chromium
        - deluge
        - epiphany-browser
        - evince
        - exfalso
        - file-roller
        - gdm3
        - gnome-clocks
        - gnome-core
        - gnome-dictionary
        - gnome-disk-utility
        - gnome-documents
        - gnome-games
        - gnome-maps
        - gnome-music
        - gnome-shell
        - gnome-software
        - gnome-todo
        - gnome-weather
        - lx*
        - mpv
        - papirus-icon-theme
        - parole
        - quod-libet
        - smplayer
        - spice-vdagent
        - synaptic
        - task-lxde-desktop
        - termit
        - transmission-gtk
        - uxterm
        - xsane
        - xterm
      state: absent
    
  - name: Update Python modules
    pip:
      name:
        - pip
        - yt-dlp
      state: latest
      
  - name: Schedule maintenance
    cron:
      name: "Hourly ansible-pull config"
      job: "ansible-pull -U https://github.com/ngkengwooi/desktop-config debian-i386.yml"
      minute: "0"
      user: root
