- hosts: localhost
  become: true
  tasks:   
  - name: Upgrade system
    apt:
      upgrade: dist
      update_cache: yes
      autoremove: yes    
  - name: Install packages
    package:
      name:
        - adwaita-qt
        - adwaita-qt6
        - ffmpeg
        - filezilla
        - firefox-esr
        - firmware-b43-installer
        - firmware-linux-nonfree
        - flatpak
        - gimp
        - gnome-shell-extension-caffeine
        - grsync
        - ibus-libpinyin
        - inkscape
        - lame
        - openssh-server
        - pdfarranger
        - python3-pip
        - qgnomeplatform-qt5
        - qt5-gtk-platformtheme
        - qt5-style-plugins
        - qt6-gtk-platformtheme   
        - remmina
        - rhythmbox-plugin-alternative-toolbar
        - ttf-mscorefonts-installer
        - unattended-upgrades
        - webext-ublock-origin-firefox
      state: latest
      
  - name: Uninstall packages
    package:
      name:
        - chromium
        - frogatto
        - gnome-games
        - gnome-software
        - gnome-software-plugin-flatpak
        - synaptic
        - transmission-gtk
      state: absent
    
  - name: Enable FlatHub
    flatpak_remote:
      name: flathub
      flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
      method: system
      state: present
      
  #- name: Install flatpaks
  #  flatpak:
  #    name: "{{item}}"
  #    method: system
  #    state: present
  #  with_items:
  #    - org.zotero.Zotero
  #    - us.zoom.Zoom
  #  when: ansible_architecture == "x86_64"
    
  #- name: Uninstall flatpaks
  #  flatpak:
  #    name: "{{item}}"
  #    method: system
  #    state: absent
  #  with_items:
  #    - com.prusa3d.PrusaSlicer
  #    - org.freecadweb.FreeCAD
  #    - org.mozilla.firefox
  #  when: ansible_architecture == "x86_64"
