- hosts: localhost
  become: true
  tasks: 
  
  - name: Upgrade system
    apt:
      upgrade: dist
      update_cache: yes
      autoremove: yes
      
  - name: Install packages
    package:
      name:
        - adwaita-qt
        - audacity
        - brasero
        - evolution-ews
        - ffmpeg
        - filezilla
        - firefox-esr
        - firmware-linux-nonfree
        - flatpak
        - frogatto
        - gimp
        - gnome-dictionary
        - gnome-mastermind
        - gnome-shell-extension-appindicator
        - gnome-shell-extension-caffeine
        - gnome-subtitles
        - grsync
        - gufw
        - handbrake
        - ibus-libpinyin
        - imagej
        - inkscape
        - lame
        - lyx
        - mkvtoolnix-gui
        - mp3wrap
        - musescore3
        - nautilus-nextcloud
        - nextcloud-desktop
        - openssh-server
        - pandoc
        - pdfarranger
        - python3-pip
        - pronterface
        - prusa-slicer
        - puddletag
        - qgnomeplatform-qt5
        - qrencode
        - qt5-gtk-platformtheme
        - qt5-style-plugins
        - qt6-gtk-platformtheme
        - remmina
        - rhythmbox-plugin-alternative-toolbar
        - simplescreenrecorder
        - soundconverter
        - sound-juicer
        - ttf-mscorefonts-installer
        - unattended-upgrades
        - unrar
        - webext-ublock-origin-firefox
      state: latest
      
  - name: Uninstall packages
    package:
      name:
        - 0ad
        - blender
        - chromium
        - clamtk
        - epiphany-browser
        - fonts-arphic-*
        - freecad
        - gchempaint
        - gcu-bin
        - ghostwriter
        - gnome-software-plugin-flatpak
        - homebank
        - keepassxc
        - openttd
        - pitivi
        - r-base
        - r-cran-rcmdr
        - scribus
        - sigil
        - steam-devices
        - supertux
        - supertuxkart
        - synaptic
        - termit
        - timekpr-next
        - torbrowser-launcher
        - unknown-horizons
        - virtualbox*
        - vlc
        - warzone2100
        - webext-https-everywhere # Deprecated
        - webext-privacy-badger
        - wireguard
      state: absent      
    
  - name: Enable FlatHub
    flatpak_remote:
      name: flathub
      flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
      method: system
      state: present
      
  #- name: Install flatpaks
  #  flatpak:
  #    name: "{{item}}"
  #    method: system
  #    state: present
  #  with_items:
  #  when: ansible_architecture == "x86_64"
  
  - name: Uninstall flatpaks
    flatpak:
      name: "{{item}}"
      method: system
      state: absent
    with_items:
      - app.drey.Dialect
      - com.bitwarden.desktop
      - com.github.johnfactotum.Foliate
      - com.github.tchx84.Flatseal      
      - com.microsoft.Teams
      - com.tutanota.Tutanota
      - com.usebottles.bottles
      - com.valvesoftware.Steam
      - de.haeckerfelix.Shortwave
      - edu.mit.Scratch
      - io.freetubeapp.FreeTube
      - io.github.mimbrero.WhatsAppDesktop
      - net.lutris.Lutris
      - org.gnome.Boxes
      - org.jitsi.jitsi-meet
      - org.zotero.Zotero
      - uk.co.ibboard.cawbird
      - us.zoom.Zoom
    when: ansible_architecture == "x86_64"
    
  - name: Schedule maintenance
    cron:
      name: "Hourly ansible-pull config"
      job: "ansible-pull -U https://github.com/ngkengwooi/desktop-config debian-home.yml"
      minute: "0"
      user: root
