- hosts: localhost
  become: true
  tasks: 
  
  - name: Upgrade system
    apt:
      update_cache: true
      upgrade: dist
      autoremove: true
      purge: true
      autoclean: true
      
  - name: Install packages
    package:
      name:
        - adwaita-qt
        - apostrophe
        - audacity
        - brasero
        - clamtk
        - dialect
        - evolution-ews
        - ffmpeg
        - firefox-esr
        - firmware-linux-nonfree
        - flatpak
        - foliate
        - fonts-noto-cjk
        - fonts-noto-cjk-extra
        - fonts-roboto
        - freecad
        - gchempaint
        - gcu-bin
        - gimp
        - gnome-dictionary
        - gnome-shell-extension-appindicator
        - gnome-shell-extension-caffeine
        - gnome-software-plugin-flatpak
        - gnome-subtitles
        - grsync
        - gsound-tools
        - gufw
        - handbrake
        - ibus-libpinyin
        - imagej
        - inkscape
        - lame
        - lyx
        - mkvtoolnix-gui
        - mp3wrap
        - nautilus-nextcloud
        - nextcloud-desktop
        - obs-studio
        - openssh-server
        - pdfarranger
        - pipx
        - pitivi
        - pronterface
        - prusa-slicer
        - puddletag
        - python3-pip
        - qgnomeplatform-qt5
        - qrencode
        - qt5-gtk-platformtheme
        - qt5-style-plugins
        - qt6-gtk-platformtheme
        - remmina
        - rhythmbox-plugin-alternative-toolbar
        - sound-juicer
        - soundconverter
        - ttf-mscorefonts-installer
        - unattended-upgrades
        - unrar
        - webext-ublock-origin-firefox        
      state: latest
      
  - name: Uninstall packages
    package:
      name:
        - anthy
        - chromium
        - debian-reference-*
        - gnome-games
        - goldendict
        - hdate-applet
        - ibus-mozc
        - mlterm
        - synaptic
        - thunderbird
        - transmission-*
        - vlc
        - webext-ublock-origin-chromium
        - xiterm+thai
      state: absent
    
  - name: Enable FlatHub
    flatpak_remote:
      name: flathub
      flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
      method: system
      state: present
      
  - name: Install flatpaks
    flatpak:
      name: "{{item}}"
      method: system
      state: present
    with_items:
      - us.zoom.Zoom
      - org.zotero.Zotero
    when: ansible_architecture == "x86_64"
  
  - name: Uninstall flatpaks
    flatpak:
      name: "{{item}}"
      method: system
      state: absent
    with_items:
      - com.microsoft.Teams
    when: ansible_architecture == "x86_64"
    
  - name: Schedule maintenance
    cron:
      name: "Hourly ansible-pull config"
      job: "ansible-pull -U https://github.com/ngkengwooi/desktop-config debian-work.yml"
      minute: "0"
      user: root
