- hosts: localhost
  become: true
  tasks: 
  
  - name: Upgrade system
    apt:
      upgrade: dist
      update_cache: yes
      autoremove: yes
      
  - name: Install packages
    package:
      name:
        - adwaita-qt
        - audacity
        - brasero
        - dialect
        - evolution-ews
        - ffmpeg
        - firefox-esr
        - firmware-linux-nonfree
        - flatpak
        - foliate
        - fonts-noto-cjk
        - fonts-noto-cjk-extra
        - fonts-roboto
        - freecad
        - frogatto
        - gimp
        - gnome-boxes
        - gnome-dictionary
        - gnome-games
        - gnome-mastermind
        - gnome-shell-extension-appindicator
        - gnome-shell-extension-caffeine
        - gnome-software-plugin-flatpak
        - gnome-subtitles
        - handbrake
        - ibus-libpinyin
        - imagej
        - inkscape
        - lame
        - libvirt-clients
        - lyx
        - mkvtoolnix-gui
        - mp3wrap
        - nautilus-nextcloud
        - nextcloud-desktop
        - obs-studio
        - openssh-server
        - pdfarranger
        - pipx
        - pronterface
        - prusa-slicer
        - puddletag
        - python3-pip
        - qgnomeplatform-qt5
        - qrencode
        - qt5-gtk-platformtheme
        - qt5-style-plugins
        - qt6-gtk-platformtheme
        - remmina
        - rhythmbox-plugin-alternative-toolbar
        - sound-juicer
        - soundconverter
        - supertux
        - supertuxkart
        - ttf-mscorefonts-installer
        - unattended-upgrades
        - unknown-horizons
        - unrar
        - webext-ublock-origin-firefox
      state: latest
      
  - name: Uninstall packages
    package:
      name:
        # Web browsing        
        - chromium
        - epiphany-browser
        - webext-ublock-origin-chromium
        
        # Games
        - 0ad
        - openttd

        # Virtualisation 
        - spice-client-gtk
        - spice-webdavd

        # Other
        - blender
        - clamtk
        - fonts-arphic-*
        - gchempaint
        - gcu-bin
        - ghostwriter
        - grsync
        - gufw
        - homebank
        - keepassxc
        - musescore3
        - pandoc
        - pitivi
        - r-base
        - r-*
        - scribus
        - sigil
        - simplescreenrecorder
        - steam-devices
        - synaptic
        - termit
        - timekpr-next
        #- torbrowser-launcher
        #- virtualbox*
        - vlc
        - warzone2100
        - webext-https-everywhere # Deprecated
        - webext-privacy-badger
        - wireguard
      state: absent      
    
  - name: Enable FlatHub
    flatpak_remote:
      name: flathub
      flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
      method: system
      state: present
      
  - name: Install flatpaks
    flatpak:
      name: "{{item}}"
      method: system
      state: present
    with_items:
      - com.github.tchx84.Flatseal
      - org.zotero.Zotero
    when: ansible_architecture == "x86_64"
  
  - name: Uninstall flatpaks
    flatpak:
      name: "{{item}}"
      method: system
      state: absent
    with_items:
      - app.drey.Dialect
      - com.bitwarden.desktop
      - com.github.johnfactotum.Foliate
      - com.microsoft.Teams
      - com.tutanota.Tutanota
      - com.valvesoftware.Steam
      - de.haeckerfelix.Shortwave
      - edu.mit.Scratch
      - io.freetubeapp.FreeTube
      - io.github.mimbrero.WhatsAppDesktop
      - org.chromium.Chromium
      - org.gnome.Boxes
      - uk.co.ibboard.cawbird
      - us.zoom.Zoom
    when: ansible_architecture == "x86_64"
    
  - name: Schedule maintenance
    cron:
      name: "Hourly ansible-pull config"
      job: "ansible-pull -U https://github.com/ngkengwooi/desktop-config debian-home.yml"
      minute: "0"
      user: root
