- hosts: localhost
  become: true
  tasks: 
  
  - name: Upgrade system
    apt:
      upgrade: dist
      update_cache: yes
      autoremove: yes
      
  - name: Install packages
    package:
      name:
        - adapta-gtk-theme
        - arc-theme
        - cheese
        - epiphany-browser
        - ffmpeg
        - firmware-b43-installer
        - firmware-linux-nonfree
        - gimp
        - gnome-dictionary
        - imagej
        - inkscape
        - lame
        - lightdm-gtk-greeter-settings
        - lxappearance
        - moka-icon-theme
        - p7zip-full
        - papirus-icon-theme
        - pdfarranger
        - python3-pip
        - qt5-gtk-platformtheme
        - qt5-style-plugins
        - spice-vdagent
        - task-lxde-desktop
        - ttf-mscorefonts-installer
        - unattended-upgrades
        - unrar
        - vlc
      state: latest
      
  - name: Uninstall packages
    package:
      name:
        - chromium
        - deluge
        - firefox-esr
        - gnome-core
        - gnome-disk-utility
        - gnome-shell
        - lxmusic
        - mpv
        - smplayer
        - synaptic
        - transmission
        - uxterm
        - xsane
        - xterm
      state: absent
    
  - name: Update Python modules
    pip:
      name:
        - pip
        - yt-dlp
      state: latest
      
  - name: Schedule maintenance
    cron:
      name: "Hourly ansible-pull config"
      job: "ansible-pull -U https://github.com/ngkengwooi/desktop-config debian-i386.yml"
      minute: "0"
      user: root
