- hosts: localhost
  become: true
  tasks: 
  
  - name: Upgrade system
    apt:
      upgrade: dist
      update_cache: yes
      autoremove: yes
      
  - name: Install packages
    package:
      name:
        - arc-theme
        - ffmpeg
        - firefox-esr
        - firmware-b43-installer
        - firmware-linux-nonfree
        - fonts-roboto
        - lame
        - lxappearance
        - moka-icon-theme
        - nm-tray
        - papirus-icon-theme
        - python3-pip
        - qt5-gtk-platformtheme
        - qt5-style-plugins
        - ttf-mscorefonts-installer
        - unattended-upgrades
        - webext-https-everywhere
        - webext-privacy-badger
        - webext-ublock-origin-firefox
      state: latest
      
  - name: Uninstall packages
    package:
      name:
        - chromium
        - deluge
        - epiphany-browser
        - lxmusic
        - mpv
        - smplayer
        - synaptic
        - termit
      state: absent
    
  - name: Update Python modules
    pip:
      name:
        - pip
        - yt-dlp
      state: latest
  
  - name: Uninstall youtube-dl
    pip:
      name:
        - youtube-dl
      state: absent
      
  - name: Schedule maintenance
    cron:
      name: "Hourly ansible-pull config"
      job: "ansible-pull -U https://github.com/ngkengwooi/desktop-config debian-i386.yml"
      minute: "0"
      user: root
