- hosts: localhost
  become: true
  tasks:
  
  - name: Upgrade system
    apt:
      upgrade: dist
      update_cache: yes
      autoremove: yes
      
  - name: Install packages
    package:
      name:
        - task-xfce-desktop
        - arc-theme
        - ffmpeg
        - firefox-esr
        - firmware-b43-installer
        - firmware-linux-nonfree
        - flatpak
        - fonts-cantarell
        - fonts-roboto
        - ibus-libpinyin
        - imagej
        - lame
        - lightdm-gtk-greeter-settings
        - p7zip-full
        - python3-pip
        - qt5-gtk-platformtheme
        - qt5-style-plugins        
        - ttf-mscorefonts-installer
        - unattended-upgrades
        - unrar
        - vlc
        - webext-ublock-origin-*
      state: latest
      
  - name: Uninstall packages
    package:
      name:
        - adapta-gtk-theme
        - anthy*
        - chromium
        - debian-reference*
        - deluge
        - epiphany-browser
        - evince
        - exfalso
        - fcitx*
        - gdm3
        - gnome-clocks
        - gnome-core
        - gnome-dictionary
        - gnome-documents
        - gnome-games
        - gnome-icon-theme
        - gnome-maps
        - gnome-music
        - gnome-shell
        - gnome-software
        - gnome-todo
        - gnome-weather
        - goldendict
        - mlterm*
        - mozc*
        - moka-icon-theme
        - mpv
        - papirus-icon-theme
        - parole
        - quod-libet
        - ristretto
        - smplayer
        - spice-vdagent
        - synaptic
        - task-lxde-desktop
        - termit
        - transmission-gtk
        - uxterm
        - webext-privacy-badger
        - xfburn
        - xiterm*
        - xsane
        - xterm
      state: absent
      
  - name: Enable FlatHub
    flatpak_remote:
      name: flathub
      flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
      method: system
      state: present
    
  - name: Update Python modules
    pip:
      name:
        - pip
        - yt-dlp
      state: latest
      
  - name: Install system upgrade script
    get_url:
      url: https://github.com/ngkengwooi/desktop-config/raw/main/system-upgrade
      dest: /usr/local/bin/system-upgrade
      mode: 0754
      
  - name: Schedule maintenance
    cron:
      name: "Hourly ansible-pull config"
      job: "ansible-pull -U https://github.com/ngkengwooi/desktop-config debian-lab-xfce.yml"
      minute: "0"
      user: root
