- hosts: localhost
  become: true
  tasks:
  - name: Install packages via APT
    package:
      name:
        - 0ad
        - adwaita-qt
        - audacity
        - blender
        - brasero
        - clamtk
        - evolution-ews
        - ffmpeg
        - filezilla
        - firefox-esr
        - flatpak
        - freecad
        - frogatto
        - gchempaint
        - gcu-bin
        - ghostwriter
        - gimp
        - gnome-mastermind
        - gnome-shell-extension-caffeine
        - gnome-software-plugin-flatpak
        - gnome-subtitles
        - handbrake
        - homebank
        - ibus-libpinyin
        - imagej
        - inkscape
        - keepassxc
        - lame
        - lyx
        - mkvtoolnix-gui
        - musescore3
        - nextcloud-desktop
        - pandoc
        - pdfarranger
        - python3-pip
        - pitivi
        - pronterface
        - prusa-slicer
        - puddletag
        - qt5-gtk-platformtheme
        - qt5-style-plugins
        - remmina
        - rhythmbox-plugin-alternative-toolbar
        - simplescreenrecorder
        - soundconverter
        - supertux
        - supertuxkart
        - unattended-upgrades
        - unknown-horizons
        - virtualbox
        - virtualbox-guest-additions-iso
        - warzone2100
        - webext-https-everywhere
        - webext-privacy-badger
        - webext-ublock-origin-firefox
      state: latest
    
  - name: Enable FlatHub
    flatpak_remote:
      name: flathub
      flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
      method: system
      state: present

  - name: Install flatpaks
    flatpak:
      name:
        - com.github.tchx84.Flatseal
        - com.microsoft.Teams
        - org.zotero.Zotero
        - us.zoom.Zoom
      method: system
      state: present
    when: ansible_architecture == "x86_64"
    
  - name: Update Python modules
    pip:
      name:
        - pip
        - youtube-dl
      state: latest
