- hosts: "localhost"
  become: true
  pre_tasks:
  - name: "Add RPMFusion repositories"
    dnf:
      name: "{{item}}"
      state: "latest"
      autoremove: yes
      update_cache: yes
    with_items:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm"
