- hosts: localhost
  become: true
  pre_tasks:
    - name: Enable RPMFusion repos
      dnf:
        name:
          - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-35.noarch.rpm
          - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-35.noarch.rpm
        state: latest
        update_cache: yes
        
  tasks:
  
    - name: Update all packages
      dnf:
        name: "*"
        state: latest
        update_cache: yes
  
    - name: Install packages
      dnf:  
        name:
          - 0ad
          - ansible
          - apostrophe
          - audacity
          - blender
          - brasero
          - cawbird
          - clamtk
          - evolution
          - evolution-ews
          - ffmpeg
          - filezilla
          - firefox
          - foliate
          - freecad
          - frogatto
          - gimp
          - gnome-chemistry-utils
          - gnome-subtitles
          - gnome-tweak-tool
          - handbrake
          - homebank
          - ibus-libpinyin
          - imagej
          - inkscape
          - keepassxc
          - lame
          - lyx
          - mkvtoolnix-gui
          - mozilla-https-everywhere
          - mozilla-privacy-badger
          - mozilla-ublock-origin
          - mscore
          - nextcloud-client
          - nextcloud-client-nautilus
          - pandoc
          - pdfarranger
          - pitivi
          - pronterface
          - prusa-slicer
          - puddletag
          - remmina
          - rhythmbox-alternative-toolbar
          - scratch
          - soundconverter
          - supertux
          - supertuxkart
          - VirtualBox
          - yt-dlp
        state: latest
        update_cache: yes
   
    - name: Clean up unused packages
      dnf:
        autoremove: yes
        
    - name: Enable FlatHub
      flatpak_remote:
        name: flathub
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        method: system
        state: present
        
    - name: Install flatpaks
      flatpak:
        name: "{{item}}"
        method: system
        state: present
      with_items:
        - com.github.tchx84.Flatseal
        - com.microsoft.Teams
        - io.freetubeapp.FreeTube
        - org.jitsi.jitsi-meet
        - org.zotero.Zotero
        - us.zoom.Zoom
      when: ansible_architecture == "x86_64"
      
    - name: Schedule maintenance
      cron:
        name: "Hourly System Update"
        job: "ansible-pull -U https://github.com/ngkengwooi/desktop-config fedora-home.yml"
        minute: "0"
        user: root
