- hosts: localhost
  become: true
  pre_tasks:
  - name: Add packages
    dnf:
      name: 
        - mozilla-https-everywhere
        - mozilla-privacy-badger
        - mozilla-ublock-origin
      state: latest
      update_cache: yes
