- hosts: localhost
  become: true
  
  pre_tasks:
  
  - name: Register public keys for repos
    package:
      name: "{{item}}"
      update_cache: yes
      state: latest
    with_items:
    - fasttrack-archive-keyring
  
  - name: Enable repositories
    apt_repository:
      repo: "{{item}}"
      state: present
    with_items:
    - deb https://deb.debian.org/debian/ bullseye main non-free contrib
    - deb https://deb.debian.org/debian/ bullseye-updates main contrib non-free
    - deb https://deb.debian.org/debian/ bullseye-backports main contrib non-free
    - deb-src https://deb.debian.org/debian/ sid main contrib non-free
    - deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-fasttrack main contrib
    - deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-backports-staging main contrib
    
  tasks:
  
  - name: Install system utilities
    package:
      name: "{{item}}"
      update_cache: yes
      state: latest
    with_items:
    - clamtk
    - filezilla
    - remmina
    
  - name: Configure GNOME desktop environment
    package:
      name: "{{item}}"
      update_cache: yes
      state: latest
    with_items:
    - adwaita-qt
    - flatpak
    - gnome-shell-extension-appindicator
    - gnome-shell-extension-caffeine
    - ibus-libpinyin
    - qt5-gtk-platformtheme
    - qt5-style-plugins    
    
  - name: Install 3D printing software
    package:
      name: "{{item}}"
      update_cache: yes
      state: latest
    with_items:
    - freecad
    - pronterface
    - prusa-slicer
  
  - name: Install office tools
    package:
      name: "{{item}}"
      update_cache: yes
      state: latest
    with_items:
    - evolution-ews
    - ghostwriter
    - homebank
    - keepassxc
    - libreoffice-gnome
    - lyx
    - nextcloud-desktop
    - pandoc
    - pdfarranger
    
  - name: Install scientific tools
    package:
      name: "{{item}}"
      update_cache: yes
      state: latest
    with_items:
    - gchempaint
    - gcu-bin
    - imagej
    - pspp
    - r-base
    - r-cran-rcmdr
    
  - name: Install multimedia tools
    package:
      name: "{{item}}"
      update_cache: yes
      state: latest
    with_items:
    - audacity
    - blender
    - brasero
    - ffmpeg
    - gimp
    - gnome-subtitles
    - handbrake
    - inkscape
    - lame
    - mkvtoolnix-gui
    - musescore3
    - pitivi
    - puddletag
    - rhythmbox-plugin-alternative-toolbar
    - simplescreenrecorder
    - soundconverter
    
  - name: Install Firefox ESR and add-ons
    package:
      name: "{{item}}"
      update_cache: yes
      state: latest
    with_items:
    - firefox-esr
    - webext-bulk-media-downloader
    - webext-https-everywhere
    - webext-keepassxc-browser
    - webext-privacy-badger
    - webext-ublock-origin-firefox
  
  - name: Install games
    package:
      name: "{{item}}"
      update_cache: yes
      state: latest
    with_items:
    - 0ad
    - frogatto
    - gnome-games
    - gnome-mastermind
    - supertux
    - supertuxkart
    - unknown-horizons
    - warzone2100
    
  - name: Install VirtualBox (requires Fasttrack repo)
    package:
      name: "{{item}}"
      update_cache: yes
      state: latest
    with_items:
    - virtualbox
    - virtualbox-guest-additions-iso

  - name: Install flatpaks
    flatpak:
      name: "{{item}}"
      method: system
      state: present
    with_items:
    - https://flathub.org/repo/appstream/com.microsoft.Teams.flatpakref
    - https://flathub.org/repo/appstream/org.jitsi.jitsi-meet.flatpakref
    - https://flathub.org/repo/appstream/org.mozilla.firefox.flatpakref
    - https://flathub.org/repo/appstream/org.zotero.Zotero
    - https://flathub.org/repo/appstream/us.zoom.Zoom.flatpakref
