- hosts: localhost
  become: true
  tasks:
  - name: Configure repositories
    apt_repository:
      repo: "{{item}}"
      state: present
    with_items:
      - deb https://deb.debian.org/debian/ bullseye main non-free contrib
      - deb https://deb.debian.org/debian/ bullseye-updates main contrib non-free
      - deb https://deb.debian.org/debian/ bullseye-backports main contrib non-free
      - deb-src https://deb.debian.org/debian/ sid main contrib non-free
      - deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-fasttrack main contrib
      - deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-backports-staging main contrib
  - name: Install apps
    package: 
      name: "{{item}}"
      state: latest
    with_items:
    - 0ad
    - adwaita-qt
    - audacity
    - blender
    - clamtk
    - evolution-ews
    - ffmpeg
    - flatpak
    - freecad
    - frogatto
    - gimp
    - gnome-games
    - gnome-mastermind
    - gnome-subtitles
    - handbrake
    - homebank
    - ibus-libpinyin
    - imagej
    - inkscape
    - lame
    - libreoffice
    - libreoffice-gnome
    - lyx
    - mkvtoolnix-gui
    - musescore3
    - nextcloud-desktop
    - pitivi
    - pronterface
    - prusa-slicer
    - qt5-gtk-platformtheme
    - qt5-style-plugins
    - remmina
    - rhythmbox-plugin-alternative-toolbar
    - simplescreenrecorder
    - soundconverter
    - unknown-horizons
    - virtualbox
    - virtualbox-guest-additions-iso
    - warzone2100
  - name: Uninstall apps
    package:
      name: "{{item}}"
      state: absent
    with_items:
      - firefox-esr
