- hosts: localhost
  become: true
  tasks:
  - name: Install apps
    package: name={{item}}
      state: present
    with_items:
    - firefox-esr
    - gimp
    - inkscape
    - freecad
    - prusa-slicer
    - flatpak
