- hosts: localhost
  become: true
  tasks:
  - name: Configure repositories
    apt_repository:
      repo: "{{item}}"
      state: present
    with_items:
      - deb https://deb.debian.org/debian/ bullseye main non-free contrib
      - deb https://deb.debian.org/debian/ bullseye-updates main contrib non-free
      - deb https://deb.debian.org/debian/ bullseye-backports main contrib non-free
      - deb-src https://deb.debian.org/debian/ sid main contrib non-free
      - deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-fasttrack main contrib
      - deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-backports-staging main contrib
  - name: Install apps
    package: 
      name: "{{item}}"
      state: latest
    with_items:
    - blender
    - clamtk
    - ffmpeg
    - flatpak
    - freecad
    - frogatto
    - gimp
    - gnome-mastermind
    - gnome-subtitles
    - ibus-libpinyin
    - imagej
    - inkscape
    - lame
    - mkvtoolnix-gui
    - nextcloud-desktop
    - pronterface
    - prusa-slicer
    - rhythmbox-plugin-alternative-toolbar
    - soundconverter
  - name: Uninstall apps
    package:
      name: "{{item}}"
      state: absent
    with_items:
      - firefox-esr
