- hosts: localhost
  become: true
    
  pre_tasks:
  
  - name: Register public keys for repos
    package:
      name: "{{item}}"
      update_cache: yes
      state: latest
    with_items:
      - fasttrack-archive-keyring
  
  - name: Enable repositories
    apt_repository:
      repo: "{{item}}"
      state: present
    with_items:
      - deb https://deb.debian.org/debian/ bullseye main non-free contrib
      - deb https://deb.debian.org/debian/ bullseye-updates main contrib non-free
      - deb https://deb.debian.org/debian/ bullseye-backports main contrib non-free
      - deb-src https://deb.debian.org/debian/ sid main contrib non-free
      - deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-fasttrack main contrib
      - deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-backports-staging main contrib
    
  tasks:
  
  - name: Install DEB packages from the repos
    package:
      name: "{{item}}"
      state: latest
    with_items:
      - 0ad
      - adwaita-qt
      - audacity
      - blender
      - brasero
      - clamtk
      - evolution-ews
      - ffmpeg
      - filezilla
      - firefox-esr
      - flatpak
      - freecad
      - frogatto
      - gchempaint
      - gcu-bin
      - ghostwriter
      - gimp
      - gnome-games
      - gnome-mastermind
      - gnome-shell-extension-caffeine
      - gnome-software-plugin-flatpak
      - gnome-subtitles
      - handbrake
      - homebank
      - ibus-libpinyin
      - imagej
      - inkscape
      - keepassxc
      - lame
      - libreoffice-gnome
      - lyx
      - mkvtoolnix-gui
      - musescore3
      - nextcloud-desktop
      - pandoc
      - pdfarranger
      - pitivi
      - pronterface
      - prusa-slicer
      - pspp
      - puddletag
      - qt5-gtk-platformtheme
      - qt5-style-plugins
      - r-base
      - r-cran-rcmdr
      - remmina
      - rhythmbox-plugin-alternative-toolbar
      - simplescreenrecorder
      - soundconverter
      - supertux
      - supertuxkart
      - unattended-upgrades
      - unknown-horizons
      - virtualbox
      - virtualbox-guest-additions-iso
      - warzone2100
      - webext-https-everywhere
      - webext-privacy-badger
      - webext-ublock-origin-firefox
    
  - name: Uninstall DEB packages from the repos
    package:
      name: "{{item}}"
      state: absent
    with_items:
      - chromium
      - gnome-shell-extension-appindicator
      - webext-ublock-origin-chromium
    
  - name: Install Bitwarden desktop client (x86_64)
    apt:
      deb: https://github.com/bitwarden/desktop/releases/download/v1.30.0/Bitwarden-1.30.0-amd64.deb
    when: ansible_architecture == "x86_64"

  - name: Enable Flathub repo for flatpaks
    flatpak_remote:
      name: flathub
      flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
      method: system
      state: present

  - name: Install flatpaks
    flatpak:
      name: "{{item}}"
      method: system
      state: present
    with_items:
      - com.github.tchx84.Flatseal
      - com.microsoft.Teams
      - org.jitsi.jitsi-meet
      - org.zotero.Zotero
      - us.zoom.Zoom
    when: ansible_architecture == "x86_64"
    
  - name: Uninstall flatpaks
    flatpak:
      name: "{{item}}"
      method: system
      state: absent
    with_items:
      - com.prusa3d.PrusaSlicer
      - org.freedesktop.Platform.ffmpeg-full/x86_64/21.08
      - org.mozilla.firefox
    when: ansible_architecture == "x86_64"
      
  - name: Install upstream youtube-dl
    pip:
      name: youtube-dl
      state: latest
   
  - name: Enable Adwaita theme for QT applications
    shell: echo "QT_STYLE_OVERRIDE=Adwaita" > /etc/environment 
