- hosts: localhost
  become: true
  tasks:
  - name: Enable repositories
    apt_repository:
      repo: "{{item}}"
      state: present
    with_items:
    - deb https://deb.debian.org/debian/ bullseye main non-free contrib
    - deb https://deb.debian.org/debian/ bullseye-updates main contrib non-free
    - deb https://deb.debian.org/debian/ bullseye-backports main contrib non-free
    - deb-src https://deb.debian.org/debian/ sid main contrib non-free
    - deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-fasttrack main contrib
    - deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-backports-staging main contrib
  - name: Disable repositories
    apt_repository:
      repo: "{{item}}"
      state: absent
    with_items:
    - deb https://download.jitsi.org stable/
  - name: Install apps
    package:
      name: "{{item}}"
      update_cache: yes
      state: latest
    with_items:
    - 0ad
    - adwaita-qt
    - audacity
    - brasero
    - blender
    - clamtk
    - evolution-ews
    - fasttrack-archive-keyring
    - ffmpeg
    - filezilla
    - flatpak
    - freecad
    - frogatto
    - gchempaint
    - gcu-bin
    - ghostwriter
    - gimp
    - gnome-games
    - gnome-mastermind
    - gnome-shell-extension-appindicator
    - gnome-shell-extension-caffeine
    - gnome-subtitles
    - handbrake
    - homebank
    - ibus-libpinyin
    - imagej
    - inkscape
    - keepassxc
    - lame
    - libreoffice
    - libreoffice-gnome
    - lyx
    - mkvtoolnix-gui
    - musescore3
    - nextcloud-desktop
    - pandoc
    - pdfarranger
    - pitivi
    - pronterface
    - prusa-slicer
    - pspp
    - puddletag
    - qt5-gtk-platformtheme
    - qt5-style-plugins
    - r-base
    - r-cran-rcmdr
    - remmina
    - rhythmbox-plugin-alternative-toolbar
    - simplescreenrecorder
    - soundconverter
    - supertux
    - supertuxkart
    - unknown-horizons
    - virtualbox
    - virtualbox-guest-additions-iso
    - warzone2100
  - name: Install Firefox and add-ons
    package:
      name: "{{item}}"
      state: latest
    with_items:
    - firefox-esr
    - webext-ublock-origin-firerfox
    - webext-https-everywhere
    - webext-privacy-badger
    - webext-keepassxc-browser
    - webext-bulk-media-downloader
