- hosts: localhost
  become: true
  tasks:
  - name: Configure repositories
    apt_repository:
      repo: "{{item}}"
      state: present
    with_items:
      - deb https://deb.debian.org/debian/ bullseye main non-free contrib
      - deb https://deb.debian.org/debian/ bullseye-updates main contrib non-free
      - deb https://deb.debian.org/debian/ bullseye-backports main contrib non-free
      - deb-src https://deb.debian.org/debian/ sid main contrib non-free
      - deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-fasttrack main contrib
      - deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-backports-staging main contrib
  - name: Install apps
    package: 
      name: "{{item}}"
      state: present
    with_items:
    - firefox-esr
    - gimp
    - inkscape
    - freecad
    - prusa-slicer
    - flatpak
